### ISSUE TITLE
EEG Data Decryption

### ISSUE THREAD

**Issue by YingchaoJiStone** [Codiologoist/DigitalTwins#46]
## User Story

**As a** developer,  
**I want** to decrypt  EEG Data to JSON type,  
**so that** I can visualize it as a graphical representation on the webpage.

---

## Acceptance Criteria

- [x] Implement the decoding functionalities of EEG data.
- [x] Using the Matplotlib library to plot the EEG data in the decryption code to measure whether the data is parsed correctly.
- [x] Storing decrypted data in files separately for each channel in JSON type.

---

**Comment by OmidKhodaparast2002** [comment]
This issue is done. However, since we do not push `binary_extraction` to this repo, it is not possible to make a PR for it.
