### ISSUE TITLE
Receive Data From Back-end

### ISSUE THREAD

**Issue by OmidKhodaparast2002** [Codiologoist/DigitalTwins#7]
## User Story

**As a** doctor,  
**I want** the front-end to receive the data for the patient from the back-end,  
**so that** I can plot them for visualisation and inspection.

## Acceptance Criteria

- [x] The code shall be modularised and reside in function(s) of its own for fetching data
- [x] The code shall make use of axios and sent a `GET` request to `/api/v1/patients/:id/<data-category>`. Note that the Part `/api/v1` shall already be configured in axios configuration in `Api.tsx`.
- [x] Patient data is to be received from the back-end at 10-second intervals

## Additional Information
- Note that the data sent from the back-end is a `json` object and this can shall be saved for plotting.

---

### Notes

- **Dependencies**: #6 #5

**Comment by OmidKhodaparast2002** [comment]
For now I have used 2-second intervals for receiving data. But this can be changed based on our needs

**Comment by tehreemAsif63** [comment]
As we have not received data from the backend yet, I used the TestApiEndpoints file to simulate data fetching and print the results to the console. This was to verify that the data fetching works as expected.
![image](https://github.com/user-attachments/assets/2827d247-0c93-44e6-b828-c57d8b882ec2)

The data was successfully fetched.
![image](https://github.com/user-attachments/assets/378a88e6-6a0b-425c-93d1-bb2767412de0)

I plan to delete this file and its related commands now that the test has passed to maintain clean code. However, feel free to refer to it in the future for testing purposes if needed.

**Comment by tehreemAsif63** [comment]
Currently, we have placeholder values for the patient, data category, and a 2-second time interval for fetching the data. The time interval can be adjusted later as needed. Otherwise, everything is functioning correctly.
